spring:
  application:
    name: ctts-gateway #服务名
  cloud:
    nacos:
      discovery:
        server-addr: 47.95.214.111:8848 #nacos地址
    gateway:
      routes:
        - id: ctts-user
          uri: lb://ctts-user #lb代表轮询调用
          predicates:
          - Path=/api/user/**
          filters:
          - RewritePath=/api/(?<segment>.*),/$\{segment}
server:
  port: 33001
